services:
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"   # host dùng localhost:9092
      - "29092:29092" # container khác dùng kafka:29092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,DOCKER://:29092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKER://kafka:29092
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  # services api gateway and microservices
  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: apps/api-gateway/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - KAFKA_BROKERS=kafka:29092
  #     - ENV_FILE=apps/api-gateway/.env
  #   depends_on:
  #     - kafka
  #     - auth
      # - chat
      # - filesystem
      # - notification

  # service auth microservice
  # auth:
  #   build:
  #     context: .
  #     dockerfile: apps/auth/Dockerfile
  #   environment:
  #     - KAFKA_BROKERS=kafka:29092
  #     - ENV_FILE=apps/auth/.env
    # depends_on:
    #   - kafka

# # service chat microservice
#   chat:
#     build:
#       context: .
#       dockerfile: apps/chat/Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:29092
#     depends_on:
#       - kafka

# # service filesystem microservice
#   filesystem:
#     build:
#       context: .
#       dockerfile: apps/filesystem/Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:29092
#     depends_on:
#       - kafka

# # service notification microservice
#   notification:
#     build:
#       context: .
#       dockerfile: apps/notification/Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:29092
#     depends_on:
#       - kafka

volumes:
  kafka_data:
