import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { Types } from 'mongoose';

export type KeyDocument = HydratedDocument<Key>;

/**
 * Parsed device info from the User-Agent header. All fields optional
 * because parsing can fail or fields can be missing (e.g. mobile webview
 * sets a custom UA that doesn't match any known browser).
 */
export class TknDeviceInfo {
  @Prop({ type: String }) browser?: string; // 'Chrome', 'Firefox', 'Safari'
  @Prop({ type: String }) browserVersion?: string; // '120.0.0'
  @Prop({ type: String }) os?: string; // 'Windows', 'macOS', 'iOS', 'Android'
  @Prop({ type: String }) osVersion?: string; // '11', '14.5'
  @Prop({ type: String }) deviceType?: string; // 'desktop', 'mobile', 'tablet', 'bot'
  @Prop({ type: String }) deviceVendor?: string; // 'Apple', 'Samsung', ...
  @Prop({ type: String }) deviceModel?: string; // 'iPhone', 'Pixel 7', ...
}

/**
 * Geo-IP lookup result. All fields optional because GeoIP database
 * may not have coverage for every IP (e.g. private/datacenter ranges).
 * Populate on login from a service like MaxMind GeoLite2 or ip-api.com.
 */
export class TknLocation {
  @Prop({ type: String }) country?: string; // 'VN', 'US' (ISO-3166-1 alpha-2)
  @Prop({ type: String }) countryName?: string; // 'Vietnam', 'United States'
  @Prop({ type: String }) region?: string; // 'Hồ Chí Minh', 'California'
  @Prop({ type: String }) city?: string; // 'Hồ Chí Minh', 'San Francisco'
  @Prop({ type: Number }) lat?: number;
  @Prop({ type: Number }) lng?: number;
  @Prop({ type: String }) timezone?: string; // 'Asia/Ho_Chi_Minh', 'America/Los_Angeles'
  @Prop({ type: String }) isp?: string; // ISP/ASN name (suspicious-login detection)
}

@Schema({ timestamps: true, collection: 'Keys' })
export class Key {
  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  tkn_userId: Types.ObjectId;

  /**
   * Stable per-device identifier. Generated by auth.service on
   * login/register and embedded in the JWT payload alongside `jti`.
   * Refresh-token rotation preserves clientId across token pairs so the
   * Keys document tracks "this device" across its entire session
   * lifetime (login → many refreshes → logout).
   *
   * NOT auto-generated in the schema — auth.service controls it
   * explicitly so the JWT and the DB row stay in lockstep.
   *
   * Composite uniqueness with `tkn_userId` is declared on the schema
   * via `index({ tkn_userId, tkn_clientId }, { unique: true })` below
   * — same user can have many devices, but each (user, device) pair
   * is one document.
   */
  @Prop({ type: String, required: true })
  tkn_clientId: string;

  /**
   * One FCM token per device — push routing now targets devices
   * directly, no need for the per-user array we used pre-multi-device.
   * String (not array) because each Keys doc IS a device session.
   */
  @Prop({ type: String, default: null })
  tkn_fcmToken: string | null;

  /**
   * Per-device JTI blacklist (revoked refresh JTIs that belonged to
   * THIS device). Refresh check inverts presence: jti in `tkn_jit` →
   * already rotated/logged-out → reject. Redis blacklist is the fast
   * path; this DB array is durable defense if Redis flushes.
   */
  @Prop({ type: [String], default: [] })
  tkn_jit: string[];

  // ── Device & origin tracking (populated on login) ────────────────────
  // Used for: security audit, suspicious-login detection, "active sessions"
  // page in user settings, geo-based fraud heuristics.

  /**
   * IP address of the client at login time. IPv4 or IPv6. For users
   * behind proxies/CDNs, prefer the X-Forwarded-For first hop over
   * req.connection.remoteAddress.
   */
  @Prop({ type: String, default: null })
  tkn_ip: string | null;

  /** Raw User-Agent header — kept for forensic / debugging needs. */
  @Prop({ type: String, default: null })
  tkn_userAgent: string | null;

  /** Parsed UA. Populate via a library like `ua-parser-js`. */
  @Prop({ type: TknDeviceInfo, default: null })
  tkn_deviceInfo: TknDeviceInfo | null;

  /** Geo-IP lookup. Populate via MaxMind / ip-api / similar. */
  @Prop({ type: TknLocation, default: null })
  tkn_location: TknLocation | null;

  /**
   * Last activity timestamp + IP. Updated on every refresh-token call.
   * Lets us detect "session active from 2 different countries within
   * 5 minutes" type anomalies + show "Last active: 2h ago" in UI.
   */
  @Prop({ type: Date, default: null })
  tkn_lastSeenAt: Date | null;

  @Prop({ type: String, default: null })
  tkn_lastSeenIp: string | null;

  // ── Soft-delete / session lifecycle ───────────────────────────────
  // Sessions are NEVER hard-deleted — each Keys row is a permanent
  // login-history entry for the account (audit trail + "where have I
  // logged in" UI). Logout flips `tkn_revokedAt` from null → Date so:
  //   - listSessions can split rows into Active vs History.
  //   - refreshToken rejects if tkn_revokedAt != null (prevents replay
  //     of a refresh token whose device was revoked from settings).
  //   - new login on the same physical device just inserts a fresh
  //     row with a fresh clientId — old row stays for the history.

  /** null = session is alive; Date = session was revoked at this time. */
  @Prop({ type: Date, default: null })
  tkn_revokedAt: Date | null;

  /**
   * Why the session was ended. Useful for the UI ("Bạn đã đăng xuất
   * thiết bị này từ trang Cài đặt" vs "Phiên hết hạn") + post-mortem
   * of suspicious activity.
   */
  @Prop({ type: String, default: null })
  tkn_revokedReason:
    | 'logout'
    | 'logout_all'
    | 'logout_device'
    | 'admin_revoke'
    | null;
}

export const KeySchema = SchemaFactory.createForClass(Key);

// Composite uniqueness: a user can have many devices, but each
// (user, device) pair maps to exactly one session document. Login
// from the SAME device upserts; login from a NEW device inserts.
KeySchema.index({ tkn_userId: 1, tkn_clientId: 1 }, { unique: true });

// Look up sessions by user (e.g. "active sessions" UI, logout-all-devices).
KeySchema.index({ tkn_userId: 1 });

export default {
  name: 'Key',
  schema: KeySchema,
};
