import type { Request } from 'express';

/**
 * Express Request augmented with the resolved auth user. Extending
 * `Request` (instead of bare `{ user }`) means callers can reach
 * standard request fields too — `req.headers`, `req.ip`,
 * `req.cookies`, etc. — without extra casting. Used by every
 * controller that depends on AuthMiddleware having run upstream.
 */
export interface AuthenticatedRequest extends Request {
  user: {
    _id: string;
    usr_id: string;
    usr_fullname: string;
    usr_email: string;
    usr_phone: string;
    usr_avatar: string;
    usr_gender: string;
    usr_status: string;
    usr_slug: string;
    usr_dateOfBirth: string;
    createdAt: string;
    updatedAt: string;
    jti: string;
    /**
     * Stable per-device id, generated by auth.service on login/register
     * and preserved across refresh-token rotations. Lets controllers
     * scope side-effects (logout, push-routing, audit logs) to the
     * caller's specific device without a separate DB lookup.
     */
    clientId: string;
    [key: string]: any;
  };
}
