export const SERVICES = {
  AUTH: 'AUTH_SERVICE',
  CHAT: 'CHAT_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
  FILESYSTEM: 'FILESYSTEM_SERVICE',
  AI: 'AI_SERVICE',
  SOCKET: 'SOCKET_SERVICE',
  LEARNING: 'LEARNING_SERVICE',
  SFU: 'SFU_SERVICE',
} as const;
