name: Deploy Socket Service

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Socket to Cloud Run
    runs-on: ubuntu-latest
    environment: 
      name: SOCKET_SERVICE
    steps:
      - uses: actions/checkout@v3

      # 1. Authenticate với Google Cloud
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Setup Gcloud SDK
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: app-chat-2b616

      # 3. Configure Docker Auth
      - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      # 4. Build và Push Docker Image
      - name: Build and Push Container
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/app-chat-2b616/microservices/socket:latest"
          docker build -t $IMAGE -f apps/socket/Dockerfile .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: socket-service
          image: asia-southeast1-docker.pkg.dev/app-chat-2b616/microservices/socket:latest
          region: asia-southeast1
          flags: '--allow-unauthenticated --min-instances=0 --max-instances=3 --cpu=1 --memory=1Gi --port=8080 --timeout=60s --use-http2'
          env_vars: |-
            NODE_ENV=${{ secrets.NODE_ENV }}
            PORT=${{ secrets.PORT }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            GATEWAY_JWT_ACCESS_SECRET=${{ secrets.GATEWAY_JWT_ACCESS_SECRET }}
            GATEWAY_CHAT_HOST=${{ secrets.GATEWAY_CHAT_HOST }}
            GATEWAY_CHAT_PORT=${{ secrets.GATEWAY_CHAT_PORT }}
            GATEWAY_CHAT_PROTO_PATH=${{ secrets.GATEWAY_CHAT_PROTO_PATH }}
            GATEWAY_FILESYSTEM_HOST=${{ secrets.GATEWAY_FILESYSTEM_HOST }}
            GATEWAY_FILESYSTEM_PORT=${{ secrets.GATEWAY_FILESYSTEM_PORT }}
            GATEWAY_NOTI_KAFKA_HOST=${{ secrets.GATEWAY_NOTI_KAFKA_HOST }}
            GATEWAY_NOTI_KAFKA_PORT=${{ secrets.GATEWAY_NOTI_KAFKA_PORT }}
            GATEWAY_NOTI_KAFKA_CLIENT_ID=${{ secrets.GATEWAY_NOTI_KAFKA_CLIENT_ID }}
            GATEWAY_NOTI_KAFKA_GROUP_ID=${{ secrets.GATEWAY_NOTI_KAFKA_GROUP_ID }}
            GATEWAY_NOTI_KAFKA_SASL=${{ secrets.GATEWAY_NOTI_KAFKA_SASL }}
            GATEWAY_NOTI_KAFKA_SASL_MECHANISM=${{ secrets.GATEWAY_NOTI_KAFKA_SASL_MECHANISM }}
            GATEWAY_NOTI_KAFKA_SASL_USERNAME=${{ secrets.GATEWAY_NOTI_KAFKA_SASL_USERNAME }}
            GATEWAY_NOTI_KAFKA_SASL_PASSWORD=${{ secrets.GATEWAY_NOTI_KAFKA_SASL_PASSWORD }}