name: Deploy Microservices

on:
  push:
    branches:
      - developer
    paths:
      - 'apps/auth/**'
      - 'apps/api-gateway/**'
      - 'apps/notification/**'
      - 'apps/filesystem/**'
      - 'apps/chat/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      service-auth: ${{steps.filter.outputs.service-auth }}
      service-api-gateway: ${{ steps.filter.outputs.service-api-gateway }}
      service-noti: ${{ steps.filter.outputs.service-noti }}
      service-filesystem: ${{ steps.filter.outputs.service-filesystem }}
      service-chat: ${{ steps.filter.outputs.service-chat }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Detect changed services
        uses: dorny/paths-filter@v3
        id: filter
        with:
          # Mỗi key (service-api-gateway, service-auth) sẽ trở thành một output (true/false)
          filters: |
            service-api-gateway:
              - 'apps/api-gateway/**'
            service-auth:
              - 'apps/auth/**'
            service-noti:
              - 'apps/notification/**'
            service-filesystem:
              - 'apps/filesystem/**'
            service-chat:
              - 'apps/chat/**'

  deploy-auth-service:
    needs:
      - detect-changes
    if: ${{ needs.detect-changes.outputs.service-auth == 'true' }}
    uses: ./.github/workflows/deploy-auth.yml
    secrets: inherit

  deploy-noti-service:
    needs:
      - detect-changes
    if: ${{ needs.detect-changes.outputs.service-noti == 'true' }}
    uses: ./.github/workflows/deploy-noti.yml
    secrets: inherit

  deploy-filesystem-service:
    needs:
      - detect-changes
    if: ${{ needs.detect-changes.outputs.service-filesystem == 'true' }}
    uses: ./.github/workflows/deploy-filesystem.yml
    secrets: inherit
  
  deploy-chat-service:
    needs:
      - detect-changes
    if: ${{ needs.detect-changes.outputs.service-chat == 'true' }}
    uses: ./.github/workflows/deploy-chat.yml
    secrets: inherit

  deploy-gateway-service:
    needs:
      - detect-changes
    if: ${{ needs.detect-changes.outputs.service-api-gateway == 'true' }}
    uses: ./.github/workflows/deploy-api-gateway.yml
    secrets: inherit
