name: Deploy Microservices

on:
  push:
    branches:
      - developer

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      service-auth: ${{ steps.filter.outputs.service-auth }}
      service-api-gateway: ${{ steps.filter.outputs.service-api-gateway }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            service-api-gateway:
              - 'apps/api-gateway/**'
            service-auth:
              - 'apps/auth/**'

  deploy-auth-service:
    needs: detect-changes
    if: ${{ inputs.deploy-service == 'auth-service' }}
    uses: ./.github/workflows/deploy-auth.yml
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-gateway-service:
    needs: detect-changes
    if: ${{ inputs.deploy-service == 'api-gateway-service' }}
    uses: ./.github/workflows/deploy-api-gateway.yml
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
