name: Deploy Microservices

on:
  push:
    branches:
      - developer

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      service-auth: ${{ steps.check-commit.outputs.service-auth }}
      service-api-gateway: ${{ steps.check-commit.outputs.service-api-gateway }}
    steps:
      - uses: actions/checkout@v4
      - id: check-commit
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == *"service/auth"* ]]; then
            echo "service-auth=true" >> $GITHUB_OUTPUT
          else
            echo "service-auth=false" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MSG" == *"service/api-gateway"* ]]; then
            echo "service-api-gateway=true" >> $GITHUB_OUTPUT
          else
            echo "service-api-gateway=false" >> $GITHUB_OUTPUT
          fi

  deploy-auth-service:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.service-auth == 'true' }}
    uses: ./.github/workflows/deploy-auth.yml
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-gateway-service:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.service-api-gateway == 'true' }}
    uses: ./.github/workflows/deploy-api-gateway.yml
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
