name: Deploy Notification Service

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Notification to Cloud Run
    runs-on: ubuntu-latest
    environment: 
      name: NOTI_SERVICE
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: app-chat-2b616
      - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
      - run: |
          IMAGE="asia-southeast1-docker.pkg.dev/app-chat-2b616/microservices/notification:latest"
          docker build -t $IMAGE -f apps/notification/Dockerfile .
          docker push $IMAGE
      - run: |
          gcloud run deploy notification-service \
            --image asia-southeast1-docker.pkg.dev/app-chat-2b616/microservices/notification:latest \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --min-instances=0 \
            --max-instances=3 \
            --cpu=1 \
            --memory=512Mi \
            --port=8080 \
            --timeout=60s \
            --use-http2 \
            --set-env-vars NODE_ENV=${{ secrets.NODE_ENV }} \
            --set-env-vars FIREBASE_TYPE=${{ secrets.FIREBASE_TYPE }} \
            --set-env-vars FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            --set-env-vars FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }} \
            --set-env-vars FIREBASE_PRIVATE_KEY='${{ secrets.FIREBASE_PRIVATE_KEY }}' \
            --set-env-vars FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} \
            --set-env-vars FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }} \
            --set-env-vars FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }} \
            --set-env-vars FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }} \
            --set-env-vars FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }} \
            --set-env-vars FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }} \
            --set-env-vars FIREBASE_UNIVERSE_DOMAIN=${{ secrets.FIREBASE_UNIVERSE_DOMAIN }} \
            --set-env-vars FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
            --set-env-vars MAIL_HOST=${{ secrets.MAIL_HOST }} \
            --set-env-vars MAIL_PORT=${{ secrets.MAIL_PORT }} \
            --set-env-vars MAIL_USER=${{ secrets.MAIL_USER }} \
            --set-env-vars MAIL_PASS=${{ secrets.MAIL_PASS }} \
            --set-env-vars KAFKA_HOST=${{ secrets.KAFKA_HOST }} \
            --set-env-vars KAFKA_PORT=${{ secrets.KAFKA_PORT }} \
            --set-env-vars KAFKA_CLIENT_ID=${{ secrets.KAFKA_CLIENT_ID }} \
            --set-env-vars KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }} \
            --set-env-vars KAFKA_SASL_MECHANISM=${{ secrets.KAFKA_SASL_MECHANISM }} \
            --set-env-vars KAFKA_SASL_USERNAME=${{ secrets.KAFKA_SASL_USERNAME }} \
            --set-env-vars KAFKA_SASL_PASSWORD=${{ secrets.KAFKA_SASL_PASSWORD }} \
            --set-env-vars APP_URL_FRONTEND=${{ secrets.APP_URL_FRONTEND }} \
            --set-env-vars REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --set-env-vars REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --set-env-vars REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} \
            --set-env-vars REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} 
