name: Deploy Filesystem Service

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Filesystem to Cloud Run
    runs-on: ubuntu-latest
    environment:
      name: FILESYSTEM_SERVICE
    steps:
      - uses: actions/checkout@v3

      # 1. Authenticate với Google Cloud
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Setup Gcloud SDK
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: project-3a90e7bd-fcfe-474a-a03

      # 3. Configure Docker Auth
      - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      # 4. Build và Push Docker Image
      - name: Build and Push Container
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/project-3a90e7bd-fcfe-474a-a03/microservices/filesystem:latest"
          docker build -t $IMAGE -f apps/filesystem/Dockerfile .
          docker push $IMAGE

      # 5. Deploy lên Cloud Run (Dùng Action tối ưu thay vì lệnh gcloud dài dòng)
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: filesystem-service
          image: asia-southeast1-docker.pkg.dev/project-3a90e7bd-fcfe-474a-a03/microservices/filesystem:latest
          region: asia-southeast1
          # Các cấu hình server: CPU, RAM, Instance, HTTP2...
          flags: '--allow-unauthenticated --min-instances=0 --max-instances=3 --cpu=1 --memory=1Gi --port=8080 --timeout=60s --use-http2'
          # Danh sách biến môi trường (Viết kiểu này an toàn cho Private Key)
          env_vars: |-
            NODE_ENV=${{ secrets.NODE_ENV }}
            HOST=${{ secrets.HOST }}
            PROTO_URL=${{ secrets.PROTO_URL }}
            S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
            S3_REGION=${{ secrets.S3_REGION }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
            DB_CONNECTION=${{ secrets.DB_CONNECTION }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            KAFKA_HOST=${{ secrets.KAFKA_HOST }}
            KAFKA_PORT=${{ secrets.KAFKA_PORT }}
            KAFKA_CLIENT_ID=${{ secrets.KAFKA_CLIENT_ID }}
            KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }}
            KAFKA_SASL=${{ secrets.KAFKA_SASL }}
            KAFKA_SASL_USERNAME=${{ secrets.KAFKA_SASL_USERNAME }}
            KAFKA_SASL_PASSWORD=${{ secrets.KAFKA_SASL_PASSWORD }}
            KAFKA_SASL_MECHANISM=${{ secrets.KAFKA_SASL_MECHANISM }}
