name: Deploy Auth Service

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Auth to Cloud Run
    runs-on: ubuntu-latest
    environment:
      name: AUTH_SERVICE
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: project-3a90e7bd-fcfe-474a-a03
      - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |
          IMAGE="asia-southeast1-docker.pkg.dev/project-3a90e7bd-fcfe-474a-a03/microservices/auth:latest"
          docker build -t $IMAGE -f apps/auth/Dockerfile .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: auth-service
          image: asia-southeast1-docker.pkg.dev/project-3a90e7bd-fcfe-474a-a03/microservices/auth:latest
          region: asia-southeast1
          flags: '--allow-unauthenticated --min-instances=0 --max-instances=3 --cpu=1 --memory=1Gi --port=8080 --timeout=60s --use-http2'
          env_vars: |-
            NODE_ENV=${{ secrets.NODE_ENV }}
            HOST=${{ secrets.HOST }}
            PROTO_PATH=${{ secrets.PROTO_PATH }}
            DB_CONNECTION=${{ secrets.DB_CONNECTION }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
            JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
